version: "2"
run:
  go: "1.25"
  tests: true
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - misspell
    - unconvert
    - testifylint
    - gosec
  disable:
    - errcheck
    - gocritic
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (*os.File).Sync
      - os.Chdir
      - os.Chmod
      - os.Chtimes
      - os.MkdirAll
      - os.Remove
      - os.RemoveAll
      - os.WriteFile
  gocritic:
    enable-all: true
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - appendAssign
      - unlambda
      - elseif
      - assignOp
      - argOrder
      - dupBranchBody
      - deprecatedComment
      - commentFormatting
      - badCall
  gosec:
    config:
      G204: "0644"
      G306: "0644"
  testifylint:
    enable-all: true

issues:
  exclude-generated: lax
  exclude-dirs-use-default: false
  exclude-use-default: false
