version: "2"
run:
  go: "1.25"
  tests: true
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - misspell
    - unconvert
    - testifylint
    - gosec
  disable:
    - errcheck
    - gocritic
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (*os.File).Sync
      - os.Chdir
      - os.Chmod
      - os.Chtimes
      - os.MkdirAll
      - os.Remove
      - os.RemoveAll
      - os.WriteFile
  gocritic:
    enable-all: true
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - appendAssign
      - unlambda
      - elseif
      - assignOp
      - argOrder
      - dupBranchBody
      - deprecatedComment
      - commentFormatting
      - badCall
  gosec:
    config:
      G204: "0644"
      G306: "0644"
  testifylint:
    enable-all: true

issues:
  exclude-generated: lax
  exclude-dirs-use-default: false
  exclude-use-default: true
  exclude-rules:
    - linters:
        - staticcheck
      text: "ST1005"
    - linters:
        - staticcheck
      text: "QF1012"
    - linters:
        - gosec
      text: "G101"
    - linters:
        - gosec
      text: "G104"
    - linters:
        - gosec
      text: "G107"
    - linters:
        - gosec
      text: "G110"
    - linters:
        - gosec
      text: "G112"
    - linters:
        - gosec
      text: "G114"
    - linters:
        - gosec
      text: "G115"
    - linters:
        - gosec
      text: "G204"
    - linters:
        - gosec
      text: "G301"
    - linters:
        - gosec
      text: "G302"
    - linters:
        - gosec
      text: "G304"
    - linters:
        - gosec
      text: "G305"
    - linters:
        - gosec
      text: "G306"
    - linters:
        - gosec
      text: "G404"
    - linters:
        - gosec
      text: "G602"
