version: "2"
run:
  go: "1.25"
  tests: true
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - misspell
    - unconvert
    # testifylint disabled due to requiring extensive test refactoring
    # gosec disabled in golangci-lint due to configuration complexity
    # Can be enabled separately with: gosec -exclude=G101,G104,G115,G301,G302,G304,G306 ./...
  disable:
    - errcheck
    - gocritic
    - revive
    - testifylint
    - gosec

linters-settings:
  # Configuration for disabled linters is kept for reference if they are re-enabled
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (*os.File).Sync
      - os.Chdir
      - os.Chmod
      - os.Chtimes
      - os.MkdirAll
      - os.Remove
      - os.RemoveAll
      - os.WriteFile
  gocritic:
    enable-all: true
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - appendAssign
      - unlambda
      - elseif
      - assignOp
      - argOrder
      - dupBranchBody
      - deprecatedComment
      - commentFormatting
      - badCall

issues:
  exclude-generated: lax
  exclude-dirs-use-default: false
  exclude-use-default: false
