version: "2"
run:
  go: "1.25"
  tests: true
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - misspell
    - unconvert
    # testifylint disabled due to requiring extensive test refactoring
    # gosec disabled in golangci-lint due to configuration complexity
    # Can be enabled separately with: gosec -exclude=G101,G104,G115,G301,G302,G304,G306 ./...
  disable:
    - errcheck
    - gocritic
    - revive
    - testifylint
    - gosec

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (*os.File).Sync
      - os.Chdir
      - os.Chmod
      - os.Chtimes
      - os.MkdirAll
      - os.Remove
      - os.RemoveAll
      - os.WriteFile
  gocritic:
    enable-all: true
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - appendAssign
      - unlambda
      - elseif
      - assignOp
      - argOrder
      - dupBranchBody
      - deprecatedComment
      - commentFormatting
      - badCall
  gosec:
    excludes:
      - G101  # Potential hardcoded credentials (acceptable in test files)
      - G104  # Unhandled errors (acceptable in test helpers)
      - G115  # Integer overflow conversion (acceptable in most cases)
      - G301  # Directory permissions (0755 is acceptable for log directories)
      - G302  # File permissions (0644 is acceptable for log files)
      - G304  # File inclusion via variable (validated file paths in tests)
      - G306  # WriteFile permissions (0644 is acceptable for non-sensitive files)
    config:
      G204: "0644"
  testifylint:
    enable-all: true

issues:
  exclude-generated: lax
  exclude-dirs-use-default: false
  exclude-use-default: false
  exclude-rules:
    # Allow unhandled errors in test files
    - linters:
        - gosec
      text: "^G104:"
      path: _test\.go
    # Allow exec.Command in integration tests (intentional usage)
    - linters:
        - gosec
      text: "^G204:"
      path: test/integration/
    # Allow exec.Command in launcher (intentional usage with validated input)
    - linters:
        - gosec
      text: "^G204:"
      path: internal/mcp/connection\.go
    # Allow HTTP requests in integration tests
    - linters:
        - gosec
      text: "^G107:"
      path: test/integration/
    # Allow ReadHeaderTimeout issues - will be addressed separately
    - linters:
        - gosec
      text: "^G112:"
    # Allow net/http serve function - will be addressed separately
    - linters:
        - gosec
      text: "^G114:"
